---
php_conf_path: /etc/php5/apache2
php_extension_conf_path: /etc/php5/conf.d
php_apc_conf_filename: 20-apc.ini
__php_packages:
  - php5
  - libapache2-mod-php5
  - php5-cli
  - php5-common
  - php5-curl
  - php5-mcrypt
  - php5-gd
  - php-pear
  - php5-imagick
  - sqlite
  - php5-sqlite
php_webserver_daemon: "apache2"
