---
apache_listen_port: 80

apache_mods_enabled:
  - rewrite.load

apache_create_vhosts: false

apache_vhosts:
  # Additional properties: 'serveradmin, extra_parameters'.
  - {servername: "local.dev", documentroot: "/var/www"}
